package gui;

import java.awt.event.ActionListener;
import modelos.Empresa;
import simulador.Simulador;

public class PainelRodada extends javax.swing.JPanel {

    private final Simulador simulador;
    private final ActionListener acaoSimular;
    
    public PainelRodada(Simulador simulador, ActionListener acaoSimular) {
        initComponents();
        this.acaoSimular = acaoSimular;
        this.simulador = simulador;
        configurarComponentes();
    }
    
    private void configurarComponentes(){
        atualizar();
        botaoSimular.addActionListener(acaoSimular);
    }
    
    public void atualizar(){
        painelTab.removeAll();
        
        for (Empresa empresa : simulador.getListaJogador()) {
            painelTab.add(empresa.getNome(), new PainelEmpresaRodada(empresa));
        }
        
        for (Empresa empresa : simulador.getListaIA()) {
            painelTab.add(empresa.getNome(), new PainelEmpresaRodada(empresa));
        }
        
        if (!simulador.acabou()){
            labelRodada.setText("Rodada " + simulador.getRodadaAtual()+"/"+simulador.getRodadasTotal());
            labelDemanda.setText("Demanda: " + simulador.getDemandaPorRodada() + " carros");
        }
    }
    
    public void venceu(ActionListener novaAcao, Empresa empresa){
        botaoSimular.setText("Novo Jogo");
        botaoSimular.removeActionListener(acaoSimular);
        botaoSimular.addActionListener(novaAcao);
        labelRodada.setText(empresa.getNome()+" venceu!");
        labelDemanda.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoSimular = new javax.swing.JButton();
        labelRodada = new javax.swing.JLabel();
        labelDemanda = new javax.swing.JLabel();
        painelTab = new javax.swing.JTabbedPane();

        botaoSimular.setText("Simular Rodada");
        botaoSimular.setActionCommand("SimularRodada");

        labelRodada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelRodada.setText("Rodada");

        labelDemanda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDemanda.setText("Demanda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRodada)
                .addGap(34, 34, 34)
                .addComponent(labelDemanda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(botaoSimular)
                .addContainerGap())
            .addComponent(painelTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTab, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoSimular, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(labelDemanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRodada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSimular;
    private javax.swing.JLabel labelDemanda;
    private javax.swing.JLabel labelRodada;
    private javax.swing.JTabbedPane painelTab;
    // End of variables declaration//GEN-END:variables
}
