/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author João Otávio
 */
public class PainelInicial extends javax.swing.JPanel {

    private ButtonGroup grupoRadio;
    
    public PainelInicial() {
        initComponents();
        configurarComponentes();
    }
    
    private void configurarComponentes(){
        grupoRadio = new ButtonGroup();
        grupoRadio.add(radioPvsP);
        grupoRadio.add(radioPvsPC);
        grupoRadio.add(radioPCvsPC);
        
        radioPCvsPC.setSelected(true);
        
        spinnerNumEmpresas.setModel(new SpinnerNumberModel(2, 2, 15, 1));
        
        botaoIniciar.addActionListener(new AcaoBotaoIniciar());
    }
    
    private class AcaoBotaoIniciar implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNumEmpresas = new javax.swing.JLabel();
        spinnerNumEmpresas = new javax.swing.JSpinner();
        botaoIniciar = new javax.swing.JButton();
        radioPCvsPC = new javax.swing.JRadioButton();
        radioPvsPC = new javax.swing.JRadioButton();
        radioPvsP = new javax.swing.JRadioButton();

        labelNumEmpresas.setText("Número de Empresas");

        botaoIniciar.setText("Iniciar");
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        radioPCvsPC.setText("Computador versus Computador");
        radioPCvsPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPCvsPCActionPerformed(evt);
            }
        });

        radioPvsPC.setText("Pessoa versus Computador");
        radioPvsPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPvsPCActionPerformed(evt);
            }
        });

        radioPvsP.setText("Pessoa versus Pessoa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNumEmpresas)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerNumEmpresas))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioPvsP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(botaoIniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioPvsPC)
                            .addComponent(radioPCvsPC))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumEmpresas)
                    .addComponent(spinnerNumEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioPCvsPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioPvsPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioPvsP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(botaoIniciar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioPCvsPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPCvsPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPCvsPCActionPerformed

    private void radioPvsPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPvsPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPvsPCActionPerformed

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoIniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JLabel labelNumEmpresas;
    private javax.swing.JRadioButton radioPCvsPC;
    private javax.swing.JRadioButton radioPvsP;
    private javax.swing.JRadioButton radioPvsPC;
    private javax.swing.JSpinner spinnerNumEmpresas;
    // End of variables declaration//GEN-END:variables
}
