package gui;

import java.util.logging.Level;
import java.util.logging.Logger;

public class PainelLoading extends javax.swing.JPanel {

    /**
     * Creates new form PainelLoading
     */
    public PainelLoading() {
        initComponents();
        configurarComponentes();
    }
    
    private Thread thread;
    
    private void configurarComponentes(){
        barLoading.setMinimum(0);
        barLoading.setMaximum(100);
        thread = new Thread(new Loading());
    }
    
    public void executar(){
        thread.start();
    }
    
    private class Loading implements Runnable {
        @Override
        public void run() {
            for (int i = 0; i < 100; i++) {
                barLoading.setValue(i);
                try {
                    Thread.sleep(20);
                } catch (InterruptedException ex) {
                    Logger.getLogger(PainelLoading.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barLoading = new javax.swing.JProgressBar();
        labelSimulando = new javax.swing.JLabel();

        labelSimulando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSimulando.setText("Simulando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(labelSimulando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(barLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSimulando)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barLoading;
    private javax.swing.JLabel labelSimulando;
    // End of variables declaration//GEN-END:variables
}
