/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Hashtable;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import simulador.Carro;

/**
 *
 * @author João Otávio
 */
public class PainelEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form PainelEmpresa
     */
    public PainelEmpresa(String titulo) {
        initComponents();
        setBorder(BorderFactory.createTitledBorder(titulo));
        configurarComponentes();
    }
    
    private void configurarComponentes(){
        Hashtable<Integer, JLabel> labelTable = new Hashtable<>();
        labelTable.put(1, new JLabel("<html><center>Baixo</center></br>R$ 1.000.000</html>"));
        labelTable.put(2, new JLabel("<html><center>Médio</center></br>R$ 5.000.000</html>"));
        labelTable.put(3, new JLabel("<html><center>Alto</center></br>R$ 10.000.000</html>"));
        sliderInvestimento.setLabelTable(labelTable);
        sliderInvestimento.setMaximum(3);
        sliderInvestimento.setMinimum(1);
        sliderInvestimento.setMajorTickSpacing(1);
        sliderInvestimento.setSnapToTicks(true);
        sliderInvestimento.setPaintLabels(true);
        sliderInvestimento.setPaintTicks(true);
        
        String[] tiposFabrica = {"Pequena", "Média", "Grande"};
        comboFabrica.setModel(new DefaultComboBoxModel(tiposFabrica));
        
        String[] tiposCarros = {"Popular", "Médio", "Luxo"};
        comboCarro.setModel(new DefaultComboBoxModel(tiposCarros));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        labelNomeEmpresa = new javax.swing.JLabel();
        campoNomeEmpresa = new javax.swing.JTextField();
        labelInvestimento = new javax.swing.JLabel();
        sliderInvestimento = new javax.swing.JSlider();
        labelFabrica = new javax.swing.JLabel();
        comboFabrica = new javax.swing.JComboBox<>();
        labelCarro = new javax.swing.JLabel();
        comboCarro = new javax.swing.JComboBox<>();
        painelInfo = new javax.swing.JPanel();
        labelGasto = new javax.swing.JLabel();
        labelTempo = new javax.swing.JLabel();
        labelVerba = new javax.swing.JLabel();

        labelNomeEmpresa.setText("Nome da Empresa:");

        campoNomeEmpresa.setText("Empresa 1");

        labelInvestimento.setText("Investimento Inicial: ");

        labelFabrica.setText("Tipo de Fábrica:");

        comboFabrica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelCarro.setText("Modelo de Carro:");

        comboCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        painelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        labelGasto.setText("Gastos fixos:");

        labelTempo.setText("Tempo de fabricação do carro:");

        labelVerba.setText("Verba restante:");

        javax.swing.GroupLayout painelInfoLayout = new javax.swing.GroupLayout(painelInfo);
        painelInfo.setLayout(painelInfoLayout);
        painelInfoLayout.setHorizontalGroup(
            painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGasto)
                    .addComponent(labelTempo)
                    .addComponent(labelVerba))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelInfoLayout.setVerticalGroup(
            painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVerba)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNomeEmpresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNomeEmpresa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelInvestimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sliderInvestimento, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelFabrica)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCarro)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboCarro, 0, 80, Short.MAX_VALUE)
                            .addComponent(comboFabrica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNomeEmpresa)
                            .addComponent(campoNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sliderInvestimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFabrica)
                    .addComponent(comboFabrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCarro)
                    .addComponent(comboCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNomeEmpresa;
    private javax.swing.JComboBox<String> comboCarro;
    private javax.swing.JComboBox<String> comboFabrica;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel labelCarro;
    private javax.swing.JLabel labelFabrica;
    private javax.swing.JLabel labelGasto;
    private javax.swing.JLabel labelInvestimento;
    private javax.swing.JLabel labelNomeEmpresa;
    private javax.swing.JLabel labelTempo;
    private javax.swing.JLabel labelVerba;
    private javax.swing.JPanel painelInfo;
    private javax.swing.JSlider sliderInvestimento;
    // End of variables declaration//GEN-END:variables
}
