package gui.servidor;

import gui.AreaLog;

public class PainelLogServidor extends javax.swing.JPanel {

    private final int porta;
    private final String endereco;
    private final int totalRodadas;
    private final int totalJogadores;
    
    public PainelLogServidor(int porta, String endereco, int totalRodadas, int totalJogadores) {
        this.porta = porta;
        this.endereco = endereco;
        this.totalRodadas = totalRodadas;
        this.totalJogadores = totalJogadores;
        initComponents();
        configurarComponentes();
    }
    
    private void configurarComponentes() {
        labelIP.setText("Endereço IP do servidor: "+endereco);
        labelPorta.setText("Porta da conexão: "+porta);
        
        labelTotalRodadas.setText("Total rodadas: "+totalRodadas);
        labelRodadaAtual.setText("Rodada atual: 1");
        labelTotalJogadores.setText("Total jogadores: "+totalJogadores);
        labelJogadores.setText("Jogadores conectados: 0");
        
        areaLog.setLineWrap(true);
        areaLog.setEditable(false);
        
        scrollPane.setViewportView(AreaLog.getTextArea());
    }
    
    public void atualizarRodadaAtual(int rodada){
        labelRodadaAtual.setText("Rodada atual: "+rodada);
    }
    
    public void atualizarJogadoresConectados(int jogadores){
        labelJogadores.setText("Jogadores conectados: "+jogadores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInfoServidor = new javax.swing.JPanel();
        labelIP = new javax.swing.JLabel();
        labelPorta = new javax.swing.JLabel();
        painelInfoJogo = new javax.swing.JPanel();
        labelRodadaAtual = new javax.swing.JLabel();
        labelTotalRodadas = new javax.swing.JLabel();
        labelJogadores = new javax.swing.JLabel();
        labelTotalJogadores = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        areaLog = new javax.swing.JTextArea();

        painelInfoServidor.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Servidor"));

        labelIP.setText("Endereço IP do servidor: ");

        labelPorta.setText("Porta da conexão: ");

        javax.swing.GroupLayout painelInfoServidorLayout = new javax.swing.GroupLayout(painelInfoServidor);
        painelInfoServidor.setLayout(painelInfoServidorLayout);
        painelInfoServidorLayout.setHorizontalGroup(
            painelInfoServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoServidorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInfoServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIP)
                    .addComponent(labelPorta))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        painelInfoServidorLayout.setVerticalGroup(
            painelInfoServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoServidorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPorta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelInfoJogo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Jogo"));

        labelRodadaAtual.setText("Rodada atual: ");

        labelTotalRodadas.setText("Total rodadas: ");

        labelJogadores.setText("Jogadores conectados: ");

        labelTotalJogadores.setText("Total jogadores: ");

        javax.swing.GroupLayout painelInfoJogoLayout = new javax.swing.GroupLayout(painelInfoJogo);
        painelInfoJogo.setLayout(painelInfoJogoLayout);
        painelInfoJogoLayout.setHorizontalGroup(
            painelInfoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoJogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInfoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRodadaAtual)
                    .addComponent(labelTotalRodadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(painelInfoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJogadores)
                    .addComponent(labelTotalJogadores))
                .addGap(27, 27, 27))
        );
        painelInfoJogoLayout.setVerticalGroup(
            painelInfoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoJogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInfoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRodadaAtual)
                    .addComponent(labelJogadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelInfoJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalRodadas)
                    .addComponent(labelTotalJogadores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        areaLog.setColumns(20);
        areaLog.setRows(5);
        scrollPane.setViewportView(areaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelInfoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(painelInfoJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelInfoServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelInfoJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaLog;
    private javax.swing.JLabel labelIP;
    private javax.swing.JLabel labelJogadores;
    private javax.swing.JLabel labelPorta;
    private javax.swing.JLabel labelRodadaAtual;
    private javax.swing.JLabel labelTotalJogadores;
    private javax.swing.JLabel labelTotalRodadas;
    private javax.swing.JPanel painelInfoJogo;
    private javax.swing.JPanel painelInfoServidor;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
